version: '3.3'

services:
  db: #Container MySQL
    image: mysql:5.7 #FROM mysql:5.7
    volumes:
      - db_data:/var/lib/mysql #declaracao de volume
    restart: always #sempre que a tiver alteracao ela vai ser atualizada
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress: #Container wordpress
    depends_on: #dependencia de container
      - db
    image: wordpress:latest #FROM wordpress:latest
    ports:
      - "8000:80"
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

volumes:
  db_data: {}
networks:
  backend: 